version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app
    volumes:
      - ./app:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-frontend
    ports:
      - "8501:8501"
    command: streamlit run frontend.py --server.port=8501 --server.address=0.0.0.0
    working_dir: /app
    volumes:
      - ./app:/app
    depends_on:
      - backend
